//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordDocumentPrinterBySection {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrinterHelperMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrinterHelperMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordDocumentPrinterBySection.PrinterHelperMessages", typeof(PrinterHelperMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The document is not stapled..
        /// </summary>
        internal static string StaplingNoneMessage {
            get {
                return ResourceManager.GetString("StaplingNoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stapling not supported by the selected printer..
        /// </summary>
        internal static string StaplingNotSupportedMessage {
            get {
                return ResourceManager.GetString("StaplingNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multiple staples along the fold line. Also called saddle-stitch stapling..
        /// </summary>
        internal static string StaplingSaddleStitchMessage {
            get {
                return ResourceManager.GetString("StaplingSaddleStitchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A single staple in the lower-left corner..
        /// </summary>
        internal static string StaplingStapleBottomLeftMessage {
            get {
                return ResourceManager.GetString("StaplingStapleBottomLeftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A single staple in the lower-right corner..
        /// </summary>
        internal static string StaplingStapleBottomRightMessage {
            get {
                return ResourceManager.GetString("StaplingStapleBottomRightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two staples along the lower edge..
        /// </summary>
        internal static string StaplingStapleDualBottomMessage {
            get {
                return ResourceManager.GetString("StaplingStapleDualBottomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two staples along the left edge..
        /// </summary>
        internal static string StaplingStapleDualLeftMessage {
            get {
                return ResourceManager.GetString("StaplingStapleDualLeftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two staples along the right edge..
        /// </summary>
        internal static string StaplingStapleDualRightMessage {
            get {
                return ResourceManager.GetString("StaplingStapleDualRightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two staples along the upper edge..
        /// </summary>
        internal static string StaplingStapleDualTopMessage {
            get {
                return ResourceManager.GetString("StaplingStapleDualTopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A single staple in the upper-left corner..
        /// </summary>
        internal static string StaplingStapleTopLeftMessage {
            get {
                return ResourceManager.GetString("StaplingStapleTopLeftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A single staple in the upper-right corner..
        /// </summary>
        internal static string StaplingStapleTopRightMessage {
            get {
                return ResourceManager.GetString("StaplingStapleTopRightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The feature (whose options are represented by this enumeration) is set to an option not defined in the Print Schema..
        /// </summary>
        internal static string StaplingUnknownMessage {
            get {
                return ResourceManager.GetString("StaplingUnknownMessage", resourceCulture);
            }
        }
    }
}
